export default Images = [
    // {url:  'https://reactnative.dev/img/tiny_logo.png'},
    // {url:  'https://via.placeholder.com/600/92c952'},
    // {url: ("https://via.placeholder.com/600/92c952")},
    {url: require("../assets/adaptive-icon.png")},
    {url: require("../assets/favicon.png")},
    {url: require("../assets/icon.png")},
    {url: require("../assets/splash.png")},
    // {url: require("https://via.placeholder.com/600/24f355")},
    // {url: require("https://via.placeholder.com/600/d32776")},
    // {url: require("https://via.placeholder.com/600/f66b97")},
    // {url: require("https://via.placeholder.com/600/56a8c2")},
    // {url: require("https://via.placeholder.com/600/b0f7cc")},
    // {url: require("https://via.placeholder.com/600/54176f")},
    // {url: require("https://via.placeholder.com/600/51aa97")},
    // {url: require("https://via.placeholder.com/600/810b14")},
    // {url: require("https://via.placeholder.com/600/1ee8a4")},
];